#!/bin/bash

ip=$1

if [[ -z $1 ]]; then
		echo "sshc is a simple wraparound for the 'ssh-keygen -fR' command" 
		echo "the -f option is set to \$HOME/.ssh/known_hosts"
		echo "USAGE: sshc <host>"
		echo "e.g.:  sshc 192.168.1.10"
else
		ssh-keygen -f "$HOME/.ssh/known_hosts" -R "$ip"
fi 

